### ISSUE TITLE
./gstream_audio_video.sh

### ISSUE THREAD

**Issue by Saitama404** [srinathava/raspberry-pi-stream-audio-video#1]
I had some problems setting all up but now I got everything running except the ./gstream_audio_video.sh which gives me this output:
`pi@raspberrypi:~/www/raspberry-pi-stream-audio-video $ ./gstream_audio_video.sh
Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstTCPClientSink:tcpclientsink1: Could not open resource for reading.
Additional debug info:
gsttcpclientsink.c(366): gst_tcp_client_sink_start (): /GstPipeline:pipeline0/GstTCPClientSink:tcpclientsink1:
Failed to connect to host '127.0.0.1:9998': Connection refused
Setting pipeline to NULL ...
Freeing pipeline ...
`
Any idea what went wrong?

**Comment by alexpersian** [comment]
You need to open up the `gstream_audio_video.sh` file and change the port from 9998 to 1337

**Comment by srinathava** [comment]
Thanks @alexpersian! I'll update the code.
