### ISSUE TITLE
No package 'libsrtp' found

### ISSUE THREAD

**Issue by qbalsdon** [srinathava/raspberry-pi-stream-audio-video#2]
When running the following: ./configure --disable-websockets --disable-data-channels \
    --disable-rabbitmq --disable-docs --disable-mqtt --prefix=/opt/janus

I get the following output:

...
checking for srtp/srtp.h... yes
checking for SRTP15X... no
configure: error: Package requirements (
                                                                 libsrtp >= 1.5.0
                                                               ) were not met:

No package 'libsrtp' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SRTP15X_CFLAGS
and SRTP15X_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by alexpersian** [comment]
Ran into this same problem. It's caused by `libsrtp` not being installed before running that script. Solved this by running the following command:
`sudo apt-get install libsrtp2-dev`

The dev branch was necessary to get the requirement to be met for me.

**Comment by srinathava** [comment]
Thanks @alexpersian I'll update the instructions.

**Comment by maciek01** [comment]
does not looks like instructions were updated
